# ======================== Elasticsearch Configuration =========================

bootstrap.memory_lock: true
network.host: 0.0.0.0
path.logs: /var/vcap/sys/log/elasticsearch
path.data: /var/vcap/store/elasticsearch
node.name: <%= name %>/<%= index %>
node.attr.zone: <%= spec.az %>

node.roles: <%= p('elasticsearch.node.roles') %>

<%
  cluster_name = nil
  if_link("elasticsearch") { |elasticsearch_link| cluster_name = elasticsearch_link.p("elasticsearch.cluster_name") }
  unless cluster_name
    cluster_name = p("elasticsearch.cluster_name")
  end
%>
cluster.name: <%= cluster_name %>

<%
  master_hosts = nil
  if_link("elasticsearch") { |elasticsearch_link| master_hosts = elasticsearch_link.instances.map {|e| e.address} }
  unless master_hosts
    master_hosts = p("elasticsearch.master_hosts")
  end
%>
discovery.seed_hosts: <%= master_hosts.join(',') %>
<% if p("elasticsearch.migrate_6_to_7") %>
cluster.initial_master_nodes: <%= master_hosts.join(',') %>
<% elsif (p('elasticsearch.node.roles').to_s.include? "master") && (index == 0) %>
cluster.initial_master_nodes: <%= name %>/<%= index %>
<% end %>
<% if_p('elasticsearch.config_options') do |config_options| %>
<%= config_options.to_yaml.gsub(/---/, '') %>
<% end %>

<%- if p("elasticsearch.tls.enabled") == true -%>
xpack.security.audit.enabled: true
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: <%= p("elasticsearch.tls.mode") %>
xpack.security.http.ssl.enabled: true

<%- unless p("elasticsearch.tls.ca").blank? -%>
xpack.security.transport.ssl.certificate_authorities: "/var/vcap/packages/elasticsearch/config/tls/tls/ca_file"
xpack.security.http.ssl.certificate_authorities: "/var/vcap/packages/elasticsearch/config/tls/tls/ca_file"
<%- else raise "'elasticsearch.tls.ca' must be set when TLS is enabled!" end -%>

<%- unless p("elasticsearch.tls.cert").blank? -%>
xpack.security.transport.ssl.certificate: "/var/vcap/packages/elasticsearch/config/tls/tls/nodecert.crt"
xpack.security.http.ssl.certificate: "/var/vcap/packages/elasticsearch/config/tls/tls/nodecert.crt"
<%- else raise "'elasticsearch.tls.cert' must be set when TLS is enabled!" end -%>

<%- unless p("elasticsearch.tls.key").blank? -%>
xpack.security.transport.ssl.key: "/var/vcap/packages/elasticsearch/config/tls/tls/nodeprivkey.key"
xpack.security.http.ssl.key: "/var/vcap/packages/elasticsearch/config/tls/tls/nodeprivkey.key"
<%- else raise "'elasticsearch.tls.key' must be set when TLS is enabled!" end -%>
<%- end -%>