# bosh update-cloud-config <(bosh cloud-config) -o manifest/cloud-config-add-azure-lb.yml -v elasticsearch_lb_name=${LB_NAME}
- type: replace
  path: /vm_extensions?/name=elasticsearch-lb?
  value:
    name: elasticsearch-lb
    cloud_properties:
      load_balancer: ((elasticsearch_lb))